Rscript src/SCRNA_01_01_Seurat.R
Rscript src/SCRNA_02_01_MonocleIntegration.R
Rscript src/SCRNA_03_01_DupletDetection.R
Rscript src/SCRNA_05_01_SingleR.R
Rscript src/SCRNA_06_01_Markers.R
Rscript src/SCRNA_06_02_MergeMarkers.R
Rscript src/SCRNA_07_01_MarkerGenes.R
Rscript src/SCRNA_08_01_ProjectionInvivo.R
#Rscript src/SCRNA_08_02_ProjectionIzzo.R
Rscript src/SCRNA_08_03_ProjectionIzzo_separate.R
Rscript src/SCRNA_10_collect_UMAPs.R
Rscript src/SCRNA_20_02_RunSummaries.R
Rscript src/SCRNA_21_01_ClusterEnrichments_Mixscape_separatedGuides.R
Rscript src/SCRNA_21_02_ClusterEnrichments_noMixscape_combined.R
# Rscript src/FIG_02_scRNA_UMAPs.R
