
#!/usr/bin/env Rscript

################################################
################################################
## LOAD LIBRARIES                             ##
################################################
################################################

library(optparse)
library(edgeR)

################################################
################################################
## PARSE COMMAND-LINE PARAMETERS              ##
################################################
################################################

option_list <- list(make_option(c("-i", "--input_file"), type="character", default=NULL, help="Path to featureCounts output ", metavar="path"),
                    make_option(c("-o", "--output_file"), type="character", default=NULL, help="Path to output CPM file", metavar="path"),
                    make_option(c("-s", "--sample_file"), type="character", default=NULL, help="Path to edgeR sample file with same sampleName as the ones in input_file", metavar="path"),
                    make_option(c("-l", "--length_column"), type="integer", default=NULL, help="Index 1 based location of length column"),
                    make_option(c("-d", "--data_columns"), type="integer", default=NULL, help="Index 1 based location of the column from which we have count data")
                    )

opt_parser <- OptionParser(option_list=option_list)
opt <- parse_args(opt_parser)

if (is.null(opt$input_file)){
    print_help(opt_parser)
    stop("Input file must be supplied.", call.=FALSE)
}
if (is.null(opt$output_file)){
    print_help(opt_parser)
    stop("Output file must be supplied.", call.=FALSE)
}
if (is.null(opt$sample_file)){
    print_help(opt_parser)
    stop("Sample file must be supplied.", call.=FALSE)
}
if (is.null(opt$length_column)){
    print_help(opt_parser)
    stop("Length column number must be supplied.", call.=FALSE)
}
if (is.null(opt$data_columns)){
    print_help(opt_parser)
    stop("Data starting column must be supplied", call.=FALSE)
}

################################################
################################################
## RUN CODE                                   ##
################################################
################################################

fileIn <- opt$input_file
fileOut <- opt$output_file
sampleFile <- opt$sample_file
lenCol <- opt$length_column
dataCol <- opt$data_columns

## Importing gene expression (features count) data
Dataset = read.table(fileIn, header = TRUE, sep = "\t",row.names = 1,
                          as.is = TRUE, check.names = FALSE)

# remove extra info
lengths <- Dataset[,lenCol]
Dataset <- Dataset[,dataCol:ncol(Dataset)]

# reduce column names length following pipeline format
# (basename of first three '_' sections)
newColNames <- unlist(lapply(colnames(Dataset), function(x) 
                                tail(strsplit(x, '/')[[1]], n=1)))
newColNames <- unlist(lapply(newColNames, function(x)
                                strsplit(x, '\\.')[[1]][1]))
newColNames <- unlist(lapply(newColNames, function(x)
                                paste0(unlist(strsplit(x, '_')[[1]][1:3]), collapse='_')))                     
# if any, we remove NA introduced due to less than 3 sections
newColNames <- unlist(lapply(newColNames, function(x)
                                strsplit(x, '_NA')[[1]][1]))
colnames(Dataset) <- newColNames

## Importing sample Info (drug treatment and cell lines info)
SampleInfo = read.table(sampleFile, header = TRUE, sep = "\t",
                        check.names = FALSE)
SampleInfo = as.matrix(SampleInfo)

# Using DGElist function from edgeR package so that it would be easy to do further analysis
DGE = edgeR::DGEList(counts = Dataset, lib.size = colSums(Dataset),
                     norm.factors = calcNormFactors(Dataset, method = "TMM"), samples = SampleInfo,group = NULL,
                     genes = NULL, remove.zeros = FALSE)
# more normalization factor value for less library size samples and viceversa was generated by
# calcNormFactors in the DGEList function

cpm = edgeR::cpm(DGE)

# get RPKM
#rpkm = edgeR::rpkm(DGE, gene.length=lengths)
originalColNames <- c('interval_id', colnames(cpm))
write.table(data.frame("interval"=rownames(cpm),cpm), file=fileOut, quote=FALSE, sep="\t",
            row.names=FALSE, col.names=originalColNames)


## get normalisation factors to be used in the future
NormFactor <- calcNormFactors(object = Dataset, method = "TMM")
## raw library size:
LibSize <- colSums(Dataset)
## calculate size factors:
SizeFactors <- NormFactor * LibSize / 1000000
## Reciprocal, to be multiplied at the time to get bigwig   
SizeFactors.Reciprocal <- 1/SizeFactors
                             
# Store reciprocla values
write.table(SizeFactors.Reciprocal, 
            file=paste0(gsub('txt', '', fileOut), 'TMMscale.txt'), 
            quote=FALSE, sep="\t",
            row.names=TRUE, col.names=FALSE)
